# Generated by Django 2.2.3 on 2019-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWork',
            fields=[
                ('PendingWork_employeeid', models.IntegerField(blank=True, null=True)),
                ('PendingWork_inwardid', models.IntegerField(blank=True, null=True)),
                ('PendingWork_name', models.CharField(blank=True, max_length=256, null=True)),
                ('PendingWork_postid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pending_work',
                'managed': True,
            },
        ),
    ]
