# Generated by Django 2.2.3 on 2019-09-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inward', '__first__'),
        ('Employee', '0004_auto_20190924_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWork',
            fields=[
                ('Pendingwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('PendingWork_employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
                ('PendingWork_inwardid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inward.Inward')),
            ],
            options={
                'db_table': 'pending_work',
                'managed': True,
            },
        ),
    ]
