# Generated by Django 2.2.3 on 2019-10-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PendingWork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingwork',
            name='PendingWork_employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee'),
        ),
        migrations.AlterField(
            model_name='pendingwork',
            name='PendingWork_inwardid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inward.Inward'),
        ),
    ]
