# Generated by Django 2.2.3 on 2019-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=256)),
                ('employee_postid', models.IntegerField()),
                ('employee_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeePost',
            fields=[
                ('ep_id', models.AutoField(primary_key=True, serialize=False)),
                ('ep_details', models.TextField()),
                ('ep_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'employee_post',
                'managed': True,
            },
        ),
    ]
