# Generated by Django 2.2.3 on 2019-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_servicetype', models.CharField(max_length=255)),
                ('invoice_address', models.TextField()),
                ('invoice_amount', models.FloatField()),
                ('invoice_comments', models.TextField()),
                ('invoice_clientid', models.IntegerField()),
                ('invoice_date', models.DateField()),
            ],
            options={
                'db_table': 'invoice',
                'managed': True,
            },
        ),
    ]
