# Generated by Django 2.2.5 on 2019-09-19 15:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type_name', models.CharField(max_length=60)),
                ('account_type_details', models.TextField()),
            ],
            options={
                'db_table': 'account_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.TextField()),
                ('client_account_type', models.IntegerField()),
                ('client_office_address1', models.TextField()),
                ('client_office_address2', models.TextField()),
                ('client_office_pin', models.CharField(max_length=12)),
                ('client_phone', phone_field.models.PhoneField(max_length=31)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_type_of_dealer', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientAccountantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_acc_info_accountant_name', models.TextField()),
                ('client_acc_info_accountant_phone', models.BigIntegerField()),
                ('client_acc_info_accountant_email', models.EmailField(max_length=254)),
                ('client_acc_info_accountant_counsultant_name', models.TextField()),
                ('client_acc_info_accountant_counsultant_phone', phone_field.models.PhoneField(max_length=31)),
                ('client_acc_info_accountant_counsultant_email', models.EmailField(max_length=254)),
                ('client_acc_info_ca_name', models.TextField()),
                ('client_acc_info_ca_phone', phone_field.models.PhoneField(max_length=31)),
                ('client_acc_info_ca_email', models.EmailField(max_length=254)),
                ('client_id', models.IntegerField()),
            ],
            options={
                'db_table': 'client_accountant_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientBankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_bank_info_bank_name', models.TextField()),
                ('client_bank_info_account_no', models.BigIntegerField()),
                ('client_bank_info_branch', models.TextField()),
            ],
            options={
                'db_table': 'client_bank_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientLegalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_leg_info_date_of_incorporation', models.DateField()),
                ('client_leg_info_st_file_no', models.BigIntegerField(db_column='client_leg_info_ST_file_no')),
                ('client_leg_info_it_file_no', models.BigIntegerField(db_column='client_leg_info_IT_file_no')),
                ('client_leg_info_tds_file_no', models.BigIntegerField(db_column='client_leg_info_TDS_file_no')),
                ('client_leg_info_vat_file_no', models.BigIntegerField(db_column='client_leg_info_VAT_file_no')),
                ('client_leg_info_vat_audit_file_no', models.BigIntegerField(db_column='client_leg_info_VAT_audit_file_no')),
                ('client_leg_info_exercise_file_no', models.BigIntegerField()),
                ('client_leg_info_vat_tin_no', models.BigIntegerField(db_column='client_leg_info_VAT_tin_no')),
                ('client_leg_info_date1', models.DateField()),
                ('client_leg_info_cst_tin_no', models.BigIntegerField(db_column='client_leg_info_CST_tin_no')),
                ('client_leg_info_date2', models.DateField()),
                ('client_leg_info_service_tax_no', models.BigIntegerField()),
                ('client_leg_info_date3', models.DateField()),
                ('client_leg_info_ecc_no', models.BigIntegerField(db_column='client_leg_info_ECC_no')),
                ('client_leg_info_date4', models.DateField()),
                ('client_leg_info_pancard_no', models.BigIntegerField()),
                ('client_leg_info_tds_no', models.BigIntegerField(db_column='client_leg_info_TDS_no')),
                ('client_leg_info_firm_registration', models.BigIntegerField()),
                ('client_leg_info_iec_no', models.BigIntegerField(db_column='client_leg_info_IEC_no')),
                ('client_leg_info_elect_no', models.BigIntegerField()),
                ('client_leg_info_pte1', models.BigIntegerField(db_column='client_leg_info_PTE1')),
                ('client_leg_info_pte2', models.BigIntegerField(db_column='client_leg_info_PTE2')),
                ('client_id', models.IntegerField()),
            ],
            options={
                'db_table': 'client_legal_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_password_vat', models.TextField(db_column='client_password_VAT')),
                ('client_password_it', models.TextField(db_column='client_password_IT')),
                ('client_passwordclient_password_tds', models.TextField(db_column='client_passwordclient_password_TDS')),
                ('client_password_st', models.TextField(db_column='client_password_ST')),
                ('client_password_excise', models.TextField()),
                ('client_password_vat_unique_id', models.TextField(db_column='client_password_VAT_unique_id')),
            ],
            options={
                'db_table': 'client_password',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientSevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_service_id', models.IntegerField()),
            ],
            options={
                'db_table': 'client_sevice',
                'managed': True,
            },
        ),
    ]
