# Generated by Django 2.2.3 on 2019-10-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20191012_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='client', max_length=60),
        ),
    ]
