# Generated by Django 2.2.3 on 2019-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('outward_id', models.AutoField(primary_key=True, serialize=False)),
                ('outward_cid', models.IntegerField(blank=True, null=True)),
                ('outward_date', models.DateField(blank=True, null=True)),
                ('outward_uploaddocstatus', models.IntegerField(blank=True, null=True)),
                ('outward_iid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outward',
                'managed': True,
            },
        ),
    ]
