# Generated by Django 2.2.3 on 2019-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('outward_id', models.AutoField(primary_key=True, serialize=False)),
                ('outward_clientid', models.IntegerField()),
                ('outward_date', models.DateField()),
                ('outward_uploaddocstatus', models.IntegerField()),
                ('outward_inwardid', models.IntegerField()),
            ],
            options={
                'db_table': 'outward',
                'managed': True,
            },
        ),
    ]
