# Generated by Django 2.2.5 on 2019-09-26 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('inward_id', models.AutoField(primary_key=True, serialize=False)),
                ('inward_track', models.TextField(blank=True, null=True)),
                ('inward_posttype', models.CharField(blank=True, max_length=255, null=True)),
                ('inward_returnperiod', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('inward_month', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('inward_year', models.IntegerField()),
                ('inward_remarks', models.TextField(blank=True, null=True)),
                ('inward_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('inward_client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.Client')),
                ('inward_employeeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
            options={
                'db_table': 'inward',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InwardPostType',
            fields=[
                ('InwardPostType_id', models.AutoField(primary_key=True, serialize=False)),
                ('InwardPostType_name', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardPostType_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inward_post_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InwardTypes',
            fields=[
                ('InwardTypes_id', models.AutoField(primary_key=True, serialize=False)),
                ('InwardTypes_name', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardTypes_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inward_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InwardDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_doc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('inward_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inward.Inward')),
            ],
            options={
                'db_table': 'inward_Document',
                'managed': True,
            },
        ),
    ]
