# Generated by Django 2.2.5 on 2019-09-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardImage',
            fields=[
                ('inward_id', models.AutoField(primary_key=True, serialize=False)),
                ('inward_doc', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'inward_Images',
                'managed': True,
            },
        ),
    ]
