# Generated by Django 2.2.3 on 2019-09-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='inward_uploadfilestatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
