# Generated by Django 2.2.5 on 2019-10-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='inward_uploadfilestatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inward',
            name='inward_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
