# Generated by Django 2.2.3 on 2019-10-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0002_auto_20191005_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpendingdocument',
            name='inward_doc',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='inwarddocument',
            name='inward_doc',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
