# Generated by Django 2.2.5 on 2019-09-20 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0002_inwardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='inward_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='inward',
            name='inward_returnperiod',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
