# Generated by Django 2.2.5 on 2019-09-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0003_auto_20190920_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_doc', models.FileField(upload_to='uploads/')),
                ('inward_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inward.Inward')),
            ],
            options={
                'db_table': 'inward_Images',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='InwardImage',
        ),
    ]
