# Generated by Django 2.2.5 on 2019-09-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0002_inward_inward_uploadfilestatus'),
        ('Inward', '0003_auto_20190928_1031'),
    ]

    operations = [
    ]
