# Generated by Django 2.2.3 on 2019-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0003_auto_20191012_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardpendingdocument',
            name='inward_doc',
            field=models.FileField(default='default.png', upload_to='uploads/'),
        ),
    ]
