# Generated by Django 2.2.5 on 2019-09-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0004_merge_20190929_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingDocument',
            new_name='InwardPendingDocument',
        ),
        migrations.RenameField(
            model_name='inwardpendingdocument',
            old_name='inward_id',
            new_name='inward',
        ),
        migrations.AlterField(
            model_name='inward',
            name='inward_uploadfilestatus',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
