# Generated by Django 2.2.5 on 2019-09-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0004_auto_20190921_0112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inwarddocument',
            table='inward_Document',
        ),
    ]
