# Generated by Django 2.2.5 on 2019-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0005_auto_20191011_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwarddocument',
            name='inward_doc',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
    ]
