# Generated by Django 2.2.5 on 2019-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward', '0006_auto_20191011_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwarddocument',
            name='inward_doc',
            field=models.FileField(default='default.png', upload_to='uploads/'),
        ),
    ]
