# Generated by Django 2.2.5 on 2019-09-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inward', '__first__'),
        ('Client', '__first__'),
        ('Employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('paymenttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymenttype_details', models.TextField(blank=True, null=True)),
                ('paymenttype_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'paymenttype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feesinward',
            fields=[
                ('feesinward_id', models.AutoField(primary_key=True, serialize=False)),
                ('feesinward_date', models.DateField(blank=True, null=True)),
                ('feesinward_inward_mode_id', models.IntegerField(blank=True, null=True)),
                ('feesinward_employee_id', models.IntegerField(blank=True, null=True)),
                ('feesinward_discount', models.FloatField(blank=True, null=True)),
                ('feesinward_balance_outstanding', models.FloatField(blank=True, null=True)),
                ('feesinward_paymentdetails', models.TextField(blank=True, null=True)),
                ('feesinward_paymenttype', models.CharField(blank=True, max_length=255, null=True)),
                ('feesinward_amount', models.FloatField(blank=True, null=True)),
                ('feesinward_client_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feesinward',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('paymenttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymenttype_details', models.TextField(blank=True, null=True)),
                ('paymenttype_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'paymenttype',
                'managed': True,
            },
        ),
    ]
