# Generated by Django 2.2.3 on 2019-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feesinward',
            fields=[
                ('feesinward_id', models.AutoField(primary_key=True, serialize=False)),
                ('feesinward_date', models.DateField()),
                ('feesinward_inward_mode_id', models.IntegerField()),
                ('feesinward_employee_id', models.IntegerField()),
                ('feesinward_discount', models.FloatField()),
                ('feesinward_balance_outstanding', models.FloatField()),
                ('feesinward_paymentdetails', models.TextField()),
                ('feesinward_paymenttype', models.CharField(max_length=255)),
                ('feesinward_amount', models.FloatField()),
                ('feesinward_client_id', models.IntegerField()),
            ],
            options={
                'db_table': 'feesinward',
                'managed': True,
            },
        ),
    ]
