# Generated by Django 2.2.3 on 2019-09-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeesInward', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesinward',
            name='feesinward_paymentdetails',
        ),
        migrations.AlterField(
            model_name='feesinward',
            name='feesinward_client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.Client'),
        ),
        migrations.AlterField(
            model_name='feesinward',
            name='feesinward_employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee'),
        ),
        migrations.AlterField(
            model_name='feesinward',
            name='feesinward_inward_mode_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inward.InwardTypes'),
        ),
        migrations.AlterField(
            model_name='feesinward',
            name='feesinward_paymenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FeesInward.PaymentType'),
        ),
    ]
